services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
     - ./backend:/backend
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=sample
      - PORT=3000
      - DATABASE_URL=mysql://user:password@mysql:3306/sample
  mysql:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
